stock_analysis_trial/chip/urls.py
from django.urls import path
from . import views

app_name = 'chip'
urlpatterns = [
    path('<stock_id>/chip', views.main, name="dashboard"),
]

stock_analysis_trial/price/urls.py
from django.urls import path

from . import views

app_name = 'price'
urlpatterns = [
    path('', views.get_posted_query, name="posted_query"),
    path('<stock_id>/price', views.main, name="dashboard"),
]

stock_analysis_trial/stock_analysis_trial/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.views.generic import TemplateView
from stocks.views import main

urlpatterns = [
    path('admin/', admin.site.urls),
    path('django_plotly_dash/', include('django_plotly_dash.urls')),
    path('index/', main, name='index'),
    path('analysis/', include('price.urls')),
    path('analysis/', include('chip.urls')),
    path('analysis/', include('monthly_revenue.urls')),
    path(
        'css/styles.css',
        TemplateView.as_view(template_name='styles.css',
                             content_type='text/css'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

stock_analysis_trial/templates/base_dashboard.html
<!DOCTYPE html>
{% load static %}
{#% load plotly_dash %#}
<html>
  <head>
    <title>財報鳥</title>
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
    />
    <link rel="stylesheet" href="/css/styles.css" type="text/css" />
  </head>
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <style>
    body{
        margin: 0;
        min-width: 1200px;
        min-height: 800px;
        background-color: aliceblue;
    }
    a{
        color: black;
        text-decoration: none;
    }
    #nav{
        display: flex;
        justify-content: space-between;
        height: 10%;
        background-color: white;
    }
    #nav>div{
        display: flex;
        height:65px;
    }
    #tools{
        gap: 10px;
        width: 30%;
    }
    #tools > *{
        height:100%;
        display: flex;
        gap: 10px;
        align-items: center;
     }
    #link_div{
        width: 65%;
        justify-content: flex-end;
        font-weight: bold;
        margin-right: 2%;
    }
    #link_div>div{
        font-size: 1.1rem;
        padding: calc((65px - 1.1rem)/2) 15px;
    }
    #link_div a{
        padding-top: 25px;
    }
    #link_div>div:hover{
        background-color: whitesmoke;
    }
/*    #link_div > div:first-child, #link_div > div:last-child{
        display: none;
    }*/
    #basic_info{
        display: flex;
        flex-direction: column;
        gap: 1%;
        justify-content: center;
    }
    #contents {
        display: flex;
        height: 90%;
        flex-direction: column;
        align-items: center;
    }
    #contents > div{
        width: 90%;
        margin-top: 1%;
    }
    #dashboard {
    }
    #panel{
        display: flex;
        gap: 1%;
        background-color: aliceblue;
    }
    #panel > div{
        background-color: white;
        text-align: center;
    }
    #title{
        height: 10%;
        justify-content: center;
        background-color: white;
        display: flex;
    }
    #title > div:not(.same_trade){
        width: 40%;
        text-align: right;
    }
    .icon {
        color: lightblue;
        font-size: 20px;
    }
    .logo{
        height: 100%;
        margin-left: 10px;
    }
    .icon_button{
        margin-left: 5px;
        border: none;
        background-color: white;
        font-size: 20px;
    }
    .search_bar{
        background-color: aliceblue;
        border-color: lightgray;
        border-radius: 5px;
        padding: 5px;
        width: 80%;
    }
    .same_trade {
      position: absolute;
      height: 200px;
      width: 25%;
      top: 20%;
      right: 15%;
      box-shadow: #6da7a2a3 0px 5px 15px;
      background-color: mintcream;
      overflow: auto;
      z-index: 1;
      display: none;
      
    }
    .same_trade ul {
      padding: 0;
      list-style-type: none;
      display: flex;
      flex-direction: row;
      flex-wrap: wrap;
    }
    .same_trade li {
        width: 40%; 
        font-size: 0.8em;
        padding: 5%;
        text-align: center;
    }   
    .same_trade li:hover {
        background-color: paleturquoise;
    }
/*    @media screen and (max-width: 1300px) {
        #link_div > div:nth-child(n+6){display: none;}
        #link_div > div:first-child{display: block;}
        #link_div > div:last-child{display: block;}
    }*/
  </style>
  <script>
     window.onfocus = function(){
        window.location.reload(); }
    window.onload = function(){
        neighbors = []
        links = document.querySelectorAll("#link_div div");
        for (var i = 1; i < links.length; i++){
                if(links[i].id == 'here'){
                    here = i;
                    break;
                    }
              }
        console.log(here);
        start = Math.min(here, 4);
        neighbors = range(start, start+4);
        if (innerWidth < 1300){
                show_abbrev_links(neighbors);
            }
        }
    function range(start, end){
        var arr = [];
        for (var i = start; i < end; i++){
            arr.push(i)
        }
        return arr
        }
    function show() {
        var x = document.getElementsByClassName("same_trade")[0];
    //      console.log(x);
    //      console.log(x.style.display);
        x.style.display = (x.style.display == "block") ? "none" : "block";
        }

 //    function show_abbrev_links(name_lists){
 //        for(var i=1; i < links.length - 1; i ++){
 //            links[i].style.display = name_lists.includes(i) ? "block" : "none";
 //            }
 //        }
 //
 //    function turn_page(direction){
 //        start = (direction == 1) ? (Math.min(start + 1, 4)) : (Math.max(start - 1, 1))
 //        var new_neighbors = range(start, start+4)
 //            show_abbrev_links(new_neighbors);
 //        }
 //      window.addEventListener('resize', function small_window(){
 //          if (innerWidth < 1300){
 //             show_abbrev_links(neighbors);}
 //        else{show_abbrev_links(range(1, 8));}
 //                                    })
  </script>
  <body>
    <div id="nav">
      <div id="tools">
        <div>
            <img class='logo' src="{% static "logo_bird0.png" %}"></img>
          <!--<a href="/overview"><img class='logo' src="asset/logo_bird.png"></img></a>-->
        </div>
        <form action={% url 'price:posted_query' %} method="POST" target="_blank" >
        {% csrf_token %}
          <input
            class="search_bar"
            type="text"
            name="stock_id"
            placeholder="查詢台股代碼/公司名稱"
            list="query"
          />
          <button class="icon_button" type="submit">
            <i class="fa fa-search"></i>
          </button>
          <datalist id="query">
            {% for stock_name in stock_list %}
                <option value="{{stock_name}}">
            {% endfor %}

              <!--<option value="1101台泥">
              <option value="1102亞泥">
              <option value="1103嘉泥">
              <option value="1104環泥">-->
        </datalist>
        </form>
        <div>
          <a href="/index"
            ><button class="icon_button"><i class="fa fa-home"></i></button
          ></a>
        </div>
      </div>
      <div id='link_div'>
              {% block link_list%}{% endblock%}  
        </div>
    </div>
    <div id="contents">
        <div id="title">
            <div><h2>{{stock_id}}</h2></div>
            <div id='basic_info'>
                <div><font color="darkcyan" onclick="show()">{{industry_type}}</font></div>
                <div>{{market_type}}日期：{{listed_date}}</div>
            </div>
            <div class="same_trade">
                <ul>
                    {% block same_trade %}{% endblock %}
              <!--{#% for stock_name in same_trade%}
              <li class="companies">{{stock_name}}</li>
              {% endfor%#}-->
                </ul>
            </div>
        </div>
        <div id="panel">
            {% block main_content %}{% endblock %}
            <!--div id="left_section" style="width: 20%">
                <p>開</p>
                <p>高</p>
                <p>低</p>
                <p>收</p>
            </div>
            <div id="dashboard" style="width: 80%;">
                <p>近90日股價走勢</p>
            </div-->
        </div>
    </div>
  </body>
</html>

stock_analysis_trial/templates/chip_dashboard.html
<!DOCTYPE html>
{% extends "base_dashboard.html" %} 
{% load plotly_dash %} 
{% block link_list%}
<div><a href="{{stock_info.get_price_url}}">近期股價</a></div>
<div id="here"><a href="{{stock_info.get_chip_url}}">籌碼分析</a></div>
<div><a href="/montly_revenue">月營收表</a></div>
{% endblock %} {% block same_trade %} {%for stock_name in same_trade%}
<li>
  <a href="{{stock_name.get_price_url}}" target="_blank"
    ><font color="black">{{stock_name}}</font></a
  >
</li>
{% endfor %} {% endblock %} {% block main_content %}
<div id="dashboard" style="width: 100%">
        <!--      <p>hello</p>-->
    {% plotly_app name="Chip_Dashboard" ratio=1%}
</div>
{% endblock %}
  </div>
</div>

stock_analysis_trial/templates/index.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <title>財報鳥</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
   <link rel="stylesheet" href="/css/styles.css" type="text/css"/>
    <style>
      .back {
        background-image: url("{% static "background.jpeg"%}");
        background-repeat: no-repeat;
        background-size: cover;
        padding-top: 5%;
      }
     .flex {
        display: flex;
        justify-content: center;
        align-items: center;
        text-align: center;
      }

      .content {
        display: flex;
        justify-content: space-around;
        width: 30%; /*寬度會和back一樣*/
        margin: 1% 2%;
        font-weight: bold;
       }
      .search{
        display: flex;
        justify-content: center;
        height: 5vh;
        width: 100%;
      }
      .search > form{
        width: 60%;
        transform: translate(0, -15%)
      }
      .search_bar{
        height: 100%;
        width: 80%;
        border-radius: 5px;
        text-align: center;
        margin: 0;
      }
      .search_button {
        height: 100%;
        width: 10%;
        border: none;
        border-radius: 5px;
        background-color: skyblue;
      }
      .mid_size_font{
        font-size: 1.7rem;
    }
    .big_size_font{
        font-size: 2.5rem;
    }
    .grid{
        display: grid;
        grid-template-columns: 50% 50%; /*給兩個數字就是兩個columns*/
        grid-template-rows: 50% 50%; /*給兩個數字就是兩個columns*/
        grid-gap: 0.3rem 1rem;
        justify-content: center;
        text-align: center;
    }
    .grid > div{
        font-size: 1.2rem;
    }
    .grid p{
        margin: 0;
    }
    #logo {
        width: 45%;
      }
    #square{
        padding-right: 1rem;
        padding-left: 1rem;
        background-color: lightgray;
      }
    li{
        height: 100%;
        float: left;
      }
    </style>
  <script>
      function gesture(condition){
        var logo = document.getElementById('logo');  
        if (condition == 'smile'){
            logo.style.width = '28%';
            logo.src = "{% static "logo_bird1.png" %}";}
        else{
            logo.style.width = '20%';
            logo.src = "{% static "logo_bird0.png" %}";}
              
            }
  </script>
  </head>
  <body style="min-height: 600px;">
    <div style="height: 100%">
        <div class="flex back">
            <div class="flex" style="width: 50%; flex-direction: column">
                <img id="logo" src="{% static "logo_bird0.png" %}"></img>
                <div class="search">
                    <!--<form>-->
                    <form action={% url 'price:posted_query' %} method="POST" target="_blank">
        <!--尋找name 為 price:posted_query 的這個url, post 給他 -->
        <!--<form action="/analysis/" method="POST-->
                    {% csrf_token %}
                    <input
                class="search_bar"
                type="text"
                name="stock_id"
                id="stock_code"
                placeholder="查詢台股代碼/公司名稱"
                list="query"
                style="font-size: 100%;"
                    />
                <!--<li style="width: 8%">-->
                <button class="search_button" type="submit"><i class="fa fa-search"></i></button>
                <datalist id="query">
                    {% for stock_name in stock_list %}
                    <option value="{{stock_name}}">
                    {% endfor %}
                </datalist>
                </form>
            </div>
        </div>
      </div>
      <div class="flex" style="flex-direction: column">
          <div class="content">
            <div class='item2 mid_size_font'>{{date}}</div>
            <div class='item2 mid_size_font'><font color="{{trend}}">{{today_close}}</font></div>
          </div>
          <div class="content">
            <div>
                <div id=square class="big_size_font" style="background-color:{{trend_background}}"><a href="https://tw.stock.yahoo.com/" target="_blank"><font color:"black">大盤<br>行情</font></a></div>
            </div>
            <div class="grid">
                <div>
                    <p>昨收</p>
                    <p>{{yesterday_close}}</p>
                </div>
                <div>
                    <p>開盤</p>
                    <p>{{open}}</p>
                </div>
                <div>
                    <p>最高</p>
                    <p>{{high}}</p>
                </div>
                <div>
                    <p>最低</p>
                    <p>{{low}}</p>
                </div>
            </div>
          </div>
      </div>
    </div>
     </body>
</html>

stock_analysis_trial/templates/monthly_revenue_dashboard.html
<!DOCTYPE html>
{% extends "base_dashboard.html" %} 
{% load plotly_dash %} 
{% block link_list%}
<div><a href="{{stock_info.get_price_url}}">近期股價</a></div>
<div><a href="{{stock_info.get_chip_url}}">籌碼分析</a></div>
<div id="here"><a href="{{stock_info.get_revenue_url}}">月營收表</a></div>
{% endblock %} {% block same_trade %} {%for stock_name in same_trade%}
<li>
  <a href="{{stock_name.get_revenue_url}}" target="_blank"
    ><font color="black">{{stock_name}}</font></a
  >
</li>
{% endfor %} {% endblock %} {% block main_content %}
<div id="dashboard" style="width: 100%">
        <!--      <p>hello</p>-->
    {% plotly_app name="MonthlyRevenue_Dashboard" ratio=1%}
</div>
{% endblock %}
  </div>
</div>

stock_analysis_trial/templates/price_dashboard.html
<!DOCTYPE html>
{% extends "base_dashboard.html" %} 
{% load plotly_dash %} 
{% block link_list%}
<div id="here"><a href="{{stock_info.get_price_url}}">近期股價</a></div>
<div><a href="{{stock_info.get_chip_url}}">籌碼分析</a></div>
<div><a href="{{stock_info.get_revenue_url}}">月營收表</a></div>
{% endblock %} {% block same_trade %} {%for stock_name in same_trade%}
<li>
  <a href="{{stock_name.get_price_url}}" target="_blank"
    ><font color="black">{{stock_name}}</font></a
  >
</li>
{% endfor %} {% endblock %} {% block main_content %}
<div id="left_section" , style="width: 20%; height: 50%">
  <div style="margin: 15%; text-align: left">
    <p>{{today_date}} 行情</p>
    <p>
      開
      <mark
        style="background-color:{{open_highlight_color}}; color:{{open_color}}"
        >{{open}}</mark
      >
    </p>
    <p>
      高
      <mark
        style="background-color:{{max_highlight_color}}; color: {{max_color}}"
        >{{max}}</mark
      >
    </p>
    <p>
      低
      <mark
        style="background-color:{{min_highlight_color}}; color: {{min_color}}"
        >{{min}}</mark
      >
    </p>
    <p>
      收
      <mark
        style="background-color:{{close_highlight_color}}; color: {{close_color}}"
        >{{close}}</mark
      >
    </p>
    <p>量(張) {{volume}}</p>
    <p>昨收 {{previous_close}}</p>
    <p>漲跌 <font color="{{updown_color}}">{{updown}}</font></p>
    <p>漲跌幅 <font color="{{updown_color}}">{{amplitude}}%</font></p>
    <p />
    <p>本益比 {{PER}}</p>
    {% if punishment_duration %}
    <p><mark style="background-color: black; color: white"> 處置</mark></p>
    <p>{{punishment_duration}}</p>
    {% endif %}
    </div>
</div>
    <div id="dashboard" style="width: 80%">
        <!--      <p>hello</p>-->
      {% plotly_app name="Price_Dashboard" ratio=1%}
    </div>
    {% endblock %}
  </div>
</div>